{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "1-202255127.ipynb",
      "provenance": [],
      "authorship_tag": "ABX9TyNoYY2C9EFC525t6e/qvMjS",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/munmoom/5-BCP/blob/main/1-202255127.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 5,
      "metadata": {
        "id": "0nuXTnx1BeLC",
        "outputId": "58797c04-c46a-4da6-8755-b1dd313ef036",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "아이슬란드의 수도는 어디입니까?\n",
            "d\n",
            "오답입니다.\n",
            "터키의 수도는 어디입니까?\n",
            "d\n",
            "오답입니다.\n",
            "캐나다의 수도는 어디입니까?\n",
            "d\n",
            "오답입니다.\n",
            "뉴질랜드의 수도는 어디입니까?\n",
            "d\n",
            "오답입니다.\n",
            "스위스의 수도는 어디입니까?\n",
            "d\n",
            "오답입니다.\n",
            "네덜란드의 수도는 어디입니까?\n",
            "d\n",
            "오답입니다.\n",
            "그리스의 수도는 어디입니까?\n",
            "d\n",
            "오답입니다.\n",
            "라오스의 수도는 어디입니까?\n",
            "d\n",
            "오답입니다.\n",
            "브라질의 수도는 어디입니까?\n",
            "d\n",
            "오답입니다.\n",
            "벨기에의 수도는 어디입니까?\n",
            "d\n",
            "오답입니다.\n",
            "우간다의 수도는 어디입니까?\n",
            "d\n",
            "오답입니다.\n",
            "파라과이의 수도는 어디입니까?\n",
            "d\n",
            "오답입니다.\n",
            "총 12문제 중 수도를 맞춘 정답수는 0 입니다\n"
          ]
        }
      ],
      "source": [
        "country_capital = {'아이슬란드':'레이캬비크',\n",
        "                   '터키':'앙카라',\n",
        "                   '캐나다':'오타와',\n",
        "                   '뉴질랜드':'웰링턴',\n",
        "                   '스위스':'베른',\n",
        "                   '네덜란드':'암스테르담',\n",
        "                   '그리스':'아테네',\n",
        "                   '라오스':'비엔티안',\n",
        "                   '브라질':'브라질리아',\n",
        "                   '벨기에':'브뤼셀',\n",
        "                   '우간다':'캄팔라',\n",
        "                   '파라과이':'아순시온'}\n",
        "\n",
        "\n",
        "sco = 0\n",
        "print('아이슬란드의 수도는 어디입니까?')\n",
        "a = input()\n",
        "ans = country_capital.get('아이슬란드')\n",
        "if ans == a:\n",
        "  sco += 1\n",
        "  print('정답입니다.')\n",
        "else:\n",
        "  print('오답입니다.')\n",
        "\n",
        "\n",
        "print('터키의 수도는 어디입니까?')\n",
        "a = input()\n",
        "ans = country_capital.get('터키')\n",
        "if ans == a:\n",
        "  sco += 1\n",
        "  print('정답입니다.')\n",
        "else:\n",
        "  print('오답입니다.')\n",
        "  \n",
        "  \n",
        "\n",
        "print('캐나다의 수도는 어디입니까?')\n",
        "a = input()\n",
        "ans = country_capital.get('캐나다')\n",
        "if ans == a:\n",
        "  sco += 1\n",
        "  print('정답입니다.')\n",
        "else:\n",
        "  print('오답입니다.')\n",
        "  \n",
        "  \n",
        "\n",
        "print('뉴질랜드의 수도는 어디입니까?')\n",
        "a = input()\n",
        "ans = country_capital.get('뉴질랜드')\n",
        "if ans == a:\n",
        "  sco += 1\n",
        "  print('정답입니다.')\n",
        "else:\n",
        "  print('오답입니다.')\n",
        "  \n",
        "  \n",
        "\n",
        "print('스위스의 수도는 어디입니까?')\n",
        "a = input()\n",
        "ans = country_capital.get('스위스')\n",
        "if ans == a:\n",
        "  sco += 1\n",
        "  print('정답입니다.')\n",
        "else:\n",
        "  print('오답입니다.')\n",
        "  \n",
        "\n",
        "print('네덜란드의 수도는 어디입니까?')\n",
        "a = input()\n",
        "ans = country_capital.get('네덜란드')\n",
        "if ans == a:\n",
        "  sco += 1\n",
        "  print('정답입니다.')\n",
        "else:\n",
        "  print('오답입니다.')\n",
        "  \n",
        "\n",
        "print('그리스의 수도는 어디입니까?')\n",
        "a = input()\n",
        "ans = country_capital.get('그리스')\n",
        "if ans == a:\n",
        "  sco += 1\n",
        "  print('정답입니다.')\n",
        "else:\n",
        "  print('오답입니다.')\n",
        "  \n",
        "  \n",
        "\n",
        "print('라오스의 수도는 어디입니까?')\n",
        "a = input()\n",
        "ans = country_capital.get('라오스')\n",
        "if ans == a:\n",
        "  sco += 1\n",
        "  print('정답입니다.')\n",
        "else:\n",
        "  print('오답입니다.')\n",
        "  \n",
        "\n",
        "print('브라질의 수도는 어디입니까?')\n",
        "a = input()\n",
        "ans = country_capital.get('브라질')\n",
        "if ans == a:\n",
        "  sco += 1\n",
        "  print('정답입니다.')\n",
        "else:\n",
        "  print('오답입니다.')\n",
        "  \n",
        "\n",
        "print('벨기에의 수도는 어디입니까?')\n",
        "a = input()\n",
        "ans = country_capital.get('벨기에')\n",
        "if ans == a:\n",
        "  sco += 1\n",
        "  print('정답입니다.')\n",
        "else:\n",
        "  print('오답입니다.')\n",
        "  \n",
        "\n",
        "print('우간다의 수도는 어디입니까?')\n",
        "a = input()\n",
        "ans = country_capital.get('우간다')\n",
        "if ans == a:\n",
        "  sco += 1\n",
        "  print('정답입니다.')\n",
        "else:\n",
        "  print('오답입니다.')\n",
        "  \n",
        "\n",
        "print('파라과이의 수도는 어디입니까?')\n",
        "a = input()\n",
        "ans = country_capital.get('파라과이')\n",
        "if ans == a:\n",
        "  sco += 1\n",
        "  print('정답입니다.')\n",
        "else:\n",
        "  print('오답입니다.')\n",
        "  \n",
        "print('총 12문제 중 수도를 맞춘 정답수는', end=' ')\n",
        "print(sco, end=' ')\n",
        "print('입니다')"
      ]
    }
  ]
}